### ISSUE TITLE
[Crash] JEI and Sophisticated Core ClickHandlerEvent crash

### ISSUE THREAD

**Issue by DSMister** [P3pp3rF1y/SophisticatedCore#271]
**Minecraft version:** 1.20.1-Forge
**Forge version:** 47.3.5

**Sophisticated Core Version:** 1.20.1-0.6.26.668
**JEI version:** jei-1.20.1-forge-15.19.5.99

**Steps to Reproduce the Bug**

1. Open the Backpack/Storage GUI that has a crafting table upgrade
2. Click on recipe in JEI
3. Click the (+) button
4. Game crashes

**Modpack URL:** https://www.curseforge.com/minecraft/modpacks/crafty-colonies

**Modpack version:** 0.5-beta

**Extra Notes:** At the moment, I have warned everyone in my server to not click on the (+) button when having the backpack or storage GUI open so they won't crash.

**Crash Reports**
https://gist.github.com/DSMister/bcc1ae255ffca95b0c6b8c961af7b8b9
https://gist.github.com/DSMister/fcd13b0584569a95791dd93e956681b2

**Comment by P3pp3rF1y** [comment]
resolved in the latest release on CF

**Comment by dvo18** [comment]
It's still happening in the version for 1.19.2

Minecraft version: 1.19.2-Forge
Forge version: 43.4.0

Sophisticated Core Version: 1.19.2-0.6.4.605
JEI version: jei-1.19.2-forge-11.8.0.1030

[crash-2024-09-25_19.07.40-client.txt](https://github.com/user-attachments/files/17135563/crash-2024-09-25_19.07.40-client.txt)
